spring:
  application:
    name: data-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}

server:
  port: 9095
  error:
    whitelabel:
      enabled: true
#  servlet:
#    context-path: /data

logging:
  level:
    org.springframework.web: INFO
    org.springframework.cloud.netflix: DEBUG
    com.netcracker.mano.cm.gateway: TRACE
    org.springframework.data.elasticsearch: DEBUG
