spring:
  application:
    name: gateway-service
  cloud:
    circuit:
      breaker:
        enabled: false
    consul:
      discovery:
        healthCheckPath: /health
        healthChechInterval: 15s
        prefer-ip-address: true
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        watch:
          enabled: true

hystrix:
  command:
    default:
      circuitBreaker:
        enabled: false
#  spring:
#    cloud:
#      consul:
#        discovery:
#          serviceId: auth-server-9091
#        host: localhost
#        port: 8500
#    cloud:
#      consul:
#        discovery:
#          instanceId: ${spring.application.name}:${random.value}

#          instance-id: auth-server-9091
#          serviceName: auth-server

server:
  port: 8765
  error:
    whitelabel:
      enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.cloud.netflix: DEBUG
    com.netcracker.mano.cm.gateway: TRACE
    org.springframework.data.elasticsearch: DEBUG

zuul:
  ignoredServices: "*"
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  sensitiveHeaders: Cookie,Set-Cookie
  debug:
    request: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
      enabled: false
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      sensitiveHeaders: Cookie,Set-Cookie
    data-service:
      path: /data/**
      serviceId: data-service
#        url: http://127.0.0.1:8082/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false

#auth-service:
#  ribbon:
#    listOfServers: http://localhost:9091/api
#    ReadTimeout: 60000
#    ConnectTimeout: 60000

#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#  ServerListRefreshInterval: 1000
#  eureka:
#    enabled: false

auth-server:
  jwtSecret: a3ZzApRSDQF5E9cH3JFV1LNBzOtQEiv6OumGJudd3Ao=